import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '@/app/assert/img/favicon.png'
import '@/app/assert/img/apple-touch-icon.png'
import '@/app/assert/vendor/bootstrap/css/bootstrap.css'
import '@/app/assert/vendor/bootstrap-icons/bootstrap-icons.css'

import '@/app/assert/vendor/aos/aos.css'
import '@/app/assert/css/variables.css'
import '@/app/assert/css/main.css'
import Header from '@/app/components/header/header'
import Section1 from '@/app/components/sections/section1'
import Section2 from '@/app/components/sections/section2'
import Culture from '@/app/components/sections/culture'
import Footer from '@/app/components/footer/footer'
import LifeStyle from "./components/sections/lifeStyle";
import Bussiness from "./components/sections/bussines";


import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <main id="main">
          <Section1/>
          <Section2/>
          <Culture/>
          <Bussiness/>
          <LifeStyle/>
          
        </main>
        <Footer/>
        </body>
    </html>
  );
}
